---
title: "TidyData"
author: "Issy Belzil"
date: '2017-09-20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Summaries of 4 Data Articles 

##Data Tidying by Garrett Grolemund

To understand data and use it usefully, it should be transformed from its raw data set form. You can do this using R, but to put the data into R, first you must do data tidying. First, Grolemund requests you install R, and tidyr, devtools, and DSR packages. DSR is a collection of data sets made by Grolemund. 

Working in R, data will be easier to use if it follows 3 rules:

* Each variable is placed in its own column

* Each observation is placed in its own row

* Each value is placed in its own cell

Tidy data assumes data sets are comprised of both values and relationships. R is mostly written to take atomic vectors as input, thus allowing you to take extract them in the same form and use them in functions, etc. For order's sake, when applying functions, R applies the function to the first elements involved, then to the 2nd, and so on and so forth. 


#### The following explains how to use tidyr()
The tidyr package helps tidy your data. There are 4 functions that change the layout of the data.
* gather() and spread () uses key value pairs.

### Key Value Pairs 

2 parts: 

  1. A key: Explains what the information is describing ex. password

  2. A value: Contains the information ex. 453364

Ex. password: 453364 
Every cell contains .5 of a key value pair. 

spread() turns key value columns to tidy columns. 

library (tidyr)

**spread(table2, key, value)**: Key & Value are the column names corresponding
The values of the key column become the new column names. No relationships have been changed.

* fill - spread() will put NA into the cells that have missing values.
* convert - when a value column contains multiple types of data, new columns are created with character strings. Setting convert = true will allow spread () to run type.convert() on the new columns. The convert strings will change to doubles. 
* drop - changes how spread() uses factors in the key column. drop = false will make the factor levels not appear in the key column. Then the missing combinations will be filled with "fill"

**Gather ()** is the opposite of spread(). It puts all the column names into a single "key" column, thus all the values will then be placed into a single value column. 

Ex: gather(table4, "year", "cases", 2:3)

2:3 explains which columns should fall into the key value pair. So column 2 and 3 will be used. In the gather() case, the author is refering to keys only as old column names. (in this example, gather doubles the amount of rows)

**Separate ()** - Will split single columns into separate ones. Separating intergers in a single column is possible as well. The length of the separate should be one less than the number of names in into. 


**Unite ()** is the opposite of separate(). Combining columns into one. Ex: unite(table6, "new", century, year, sep = ""). If you would like the new table to contain the newly combined column and the old seperate ones still, type remove = FALSE 

*Use the View() function to open a data viewer in RStudio IDE. Make sure you use a capital V. 



#Tidy Data (Summary Ch. 12 from R for Data Science)

Tidyr is part of the "tidyverse":

library(tidyverse)


If your data is tidy, the advantages will be:

 1. Only having one way to store your data, it will be easier to work in projects that are already uniform. (Keep your data structure consistent) 

 2. Putting variables in the columns will allow you to use R's vector structures.


#Summary of Data Transformation Article (Chapter 5)

This chapter focuses on the dplyr package and uses: 

   * library(nycflights13) - Data frame that houses 336,776 flights that left from NYC in 2013
 
   * library(tidtverse)

Tibble: Data frames that are represented differently from the normal data frames. They are "tweaked" by tidyverse. 

  * int: integers
  
  * dbl: doubles (real numbers)
  
  * chr: character vectors & strings.
  
  * dttm: date and time.
  
  * lgl: logical vectors that are either TRUE or FALSE
  
  * fctr: factors- categorical variables with fixed possible valies 
  
  * date: dates


##Five Key dplyr Functions:

**filter()** : Will filter the data frame based on the specifications you use. It will create a new filtered data frame. If you want to save the data frame- use "<-". 

    * Ex: jan1 <- filter(flights, month == 1, day == 1). You can then save the results as a variable. 

**REMINDER**: You may use: >, >=, <, <=, != (not equal), and == (equal)
  * in filter() : & = "and" , | = "or", ! = "not". (see figure 5.1) ex: 
 
 filter(flights, month == 11 | month == 12)
 
 
  * Tip: !(x & y) = !x | !y, !(x | y) = !x & !y
  
  
  * Use is.na() to see if a value is missing. If any NA's are in an operation, the result will be NA. filter() will normally ignore NA and FALSE values. To fix, include in the code. (5.2.3)

**arrange()** : Changes the order of rows. ex: arrage(flights, year, month, day)

  * Using desc() can be useful when finding the most delayed flight, etc. 

**select()** : Very useful when there are hundreds of variables! ex: select(flights, year, month, day)
Useful functions within:

  * starts_with("abc")
  * ends_with("xyz")
  * contains("ijk")
  * matches("(.)\\1") - For selecting variables that match a regular expression. 
  * num_rang("x", 1:3) Range. 
  * rename(flights, tail_num = tailnum)
  * use everything(). select(flights, time_hour, air_time, everything()).
  
  Allowing your named variables to be the first columns, then the rest of the columns after. 

**mutate()** : Adds columns to the end of your data set. To see all the columns : View().

  EX: mutate(flights_sml,
  gain = arr_delay - dep_delay,
  speed = distance / air_time * 60)
  
  * To drop off the old variables and only keep the new ones, uses transmute() 
  * There are many ways to rank. Using min_rink() will make the small values the small ranks. 

**summarise()** : Collapses data to a singular row. Using summarise with group_by() is more useful together. 

  * Ex: by_day <- group_by(flights, year, month, day)
summarise(by_day, delay = mean(dep_delay, na.rm = TRUE)) 


*How to simplistically create an order of operations is by using "%>%" which can be read as: then. This is called working with the pipe. 

**group_by()** : changes scope of each function from the data set to focusing on group-by-group.

#Summary of dplyr 

This article outlined the two new significant updates to dplyr, 0.3 and 0.4, which includes a array of new features. There is new ways to choose columns with select and rename and choosing rows with commands like filter, between, slice, sample_n, top_n, and distinct. Users can now also add new variables by using mutate, transmute, and add_rownames. Methods for grouping and counting data have functions like:

* summarise

* tally 

* count 

* group_size

* n_groups

* ungroup


There is also a new method to create data frames. 

Data_frame is a better alternative to data. **frame()** because it never coerces column types, never munges column names, never adds row names, and only recycles length 1 input. You can also use previously defined columns to compute new columns. 

The print and view commands allow for users to easily view output. All of these features make R studio a much more user-friendly program. It is now possible for users to implement these commands in order to easily be able to add rows, count data, and display data more effectively.
